import Head from 'next/head'
import { Header } from '~/components/layout/Header'
import { Page } from '~/components/layout/Page'
import { Wrapper } from '~/components/layout/Wrapper'

export default function Home() {
  return (
    <>
      <Head>
        <title>Hungyeri</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Page>
          <Wrapper>
            <Header>Hungyeri</Header>
            <span>I am hungyeri...</span>
          </Wrapper>
        </Page>
      </main>
    </>
  )
}
